stages:
  - build
  - docker

cache:
  paths:
    - node_modules/

build-react:
  stage: build
  image: node:18-alpine
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - build/

docker-build:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker build -t my-react-app .
